name: Node.js CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: |
          npm install -g npm-force-resolutions
          npm-force-resolutions
          npm install
      - name: Test Project
        run: npm test
      - name: Typecheck Project
        run: npm run typecheck
      - name: Compile Project
        run: npm run build
